### ISSUE TITLE
Fix project compile error 'Unable to Resolve .NET SDK version as specified in the global.json...' 

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#220]
This occurs if you have a newer version of the SDK installed.  global.json specifes version 6.0.101
```json
{
  "sdk": {
    "version": "6.0.101",
    "rollForward": "disable"
  }
}
```
This file was added for issue #42 

Recently this issue occurred following installing Windows updates where it appears that the SDK was upgraded to 6.0.203 (removing 6.0.101 in the process).  To fix the issue you need to remove 6.0.203 to allow the installation of 6.0.101.  This is painful and potentially frustrating for any new users that want to work on this project.  

The only problem building with a newer version of the .NET framework is that it won't have compatibility with the older versions of the NET 6 runtime and will fail silently.  This will be less of an issue as more people upgrade their .NET runtime versions.

Also, the github action that builds the project for public release specifies the version of the .NET SDK to use:

```yml
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.101
          include-prerelease: true

```

Removing the global.json file should improve the developer experience while the public build from the github action will still use version 6.0.101 for the widest compatibility.
