### ISSUE TITLE
DB Build issue with msbuild 17.5

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#554]
DB build fails with msbuild 17.5.  Issue logged [here](https://github.com/microsoft/DacFx/issues/236)

Might need to consider workarounds

**Comment by DavidWiseman** [comment]
Fix to specify version 17.4 no longer seems to be working.

```yml
     - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3
        with:
          vs-version: '[17.4,17.5)'
```
